- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start Prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    ports: "9090:9090"
    volumes: "{{ playbook_dir }}/templates/prometheus.yml:/etc/prometheus/prometheus.yml"

- name: Start Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    ports: "3000:3000"