---
- name: Установка зависимостей
  apt:
    name:
      - openjdk-11-jdk
      - jenkins
      - ca-certificates
      - curl
    update_cache: yes

- name: Настройка параметров Jenkins
  template:
    src: jenkins_config.j2
    dest: /etc/default/jenkins
  notify: Restart Jenkins

- name: Применение базовой конфигурации
  block:
    - name: Создать конфиг JCasC
      copy:
        dest: /var/lib/jenkins/jenkins.yaml
        content: |
          jenkins:
            securityRealm:
              local:
                allowsSignup: false
                users:
                  - id: admin
                    password: "{{ jenkins_admin_password }}"
            authorizationStrategy:
              globalMatrix:
                permissions:
                  - "Overall/Administer:admin"

    - name: Создать директорию плагинов
      file:
        path: /var/lib/jenkins/plugins
        state: directory
        owner: jenkins
        group: jenkins

    - name: Обновить зеркало плагинов
      xml:
        path: /var/lib/jenkins/hudson.model.UpdateCenter.xml
        xpath: '/sites/site/id[text()="default"]/../url'
        value: "https://updates.jenkins.io/update-center.json"
  notify: Restart Jenkins

- name: Ожидать запуска Jenkins
  wait_for:
    port: 8080
    delay: 10
    timeout: 300