---
- name: Install Prometheus
  apt:
    name: prometheus
    state: present

- name: Deploy Prometheus config
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Start Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes