---
- name: настройка инфраструктуры
  hosts: all
  become: true
  roles:
    - jenkins
    - monitoring
    - app
  tasks:
    - name: Запуск Flask-приложения
      ansible.builtin.command:
        cmd: "{{ venv_path }}/bin/python app.py"
        chdir: "{{ app_path }}"
      environment:
        FLASK_APP: app.py
        FLASK_ENV: production
      async: 600
      poll: 0