---
- name: Установка и настройка инфраструктуры
  hosts: all
  become: true
  roles:
    - jenkins
    - monitoring
    - app
  tasks:
    - name: Установка зависимостей Python
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-dev
          - build-essential
        state: present
        update_cache: yes

    - name: Создание каталога для приложения
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory
        mode: 0755

    - name: Клонирование репозитория
      ansible.builtin.git:
        repo: "https://github.com/nuclear77/theGP.git"
        dest: "{{ app_src_path }}"
        version: main
        force: yes

    - name: Создание виртуального окружения
      ansible.builtin.command:
        cmd: python3 -m venv {{ venv_path }}
        creates: "{{ venv_path }}/bin/activate"

    - name: Установка зависимостей
      ansible.builtin.pip:
        requirements: "{{ app_src_path }}/requirements.txt"
        virtualenv: "{{ venv_path }}"

    - name: Запуск Flask-приложения
      ansible.builtin.command:
        cmd: "{{ venv_path }}/bin/python app.py"
        chdir: "{{ app_src_path }}"
      environment:
        FLASK_APP: app.py
        FLASK_ENV: production
      async: 600
      poll: 0