---
- name: Create logging directory
  file:
    path: "/etc/logging"
    state: directory
    mode: '0755'

- name: Start Loki
  docker_container:
    name: loki
    image: grafana/loki
    ports:
      - "3100:3100"
    restart_policy: unless-stopped

- name: Start Promtail
  docker_container:
    name: promtail
    image: grafana/promtail
    volumes:
      - "/var/log:/var/log"
      - "{{ playbook_dir }}/logging/promtail-config.yml:/etc/promtail/config.yml"
    command: "-config.file=/etc/promtail/config.yml"
    restart_policy: unless-stopped