- name: Run Loki and Promtail
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    ports: "{{ item.ports | default('') }}"
    volumes: "{{ item.volumes | default('') }}"
    command: "{{ item.command | default('') }}"
    restart_policy: unless-stopped
  loop:
    - { name: "loki", image: "grafana/loki", ports: "3100:3100" }
    - { name: "promtail", image: "grafana/promtail",
        volumes: "/var/log:/var/log",
        command: "-config.file=/etc/promtail/config.yml" }