---
- name: Deploy full infrastructure
  hosts: localhost
  become: yes
  gather_facts: yes
  roles:
    - jenkins
    - flask-app
    - prometheus
  vars:
    app_port: 6060
    service_name: "flask-app"