---
- name: Deploy Monitoring Stack
  hosts: localhost
  become: yes
  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Configure Prometheus
      copy:
        src: "{{ monitoring_config_dir }}/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml
      notify: Restart Prometheus

    - name: Ensure Prometheus service is enabled
      systemd:
        name: prometheus
        enabled: yes
        state: started

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted