---
- name: Deploy full infrastructure
  hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - secrets.yml
    - group_vars/all/vault.yml
  roles:
    - jenkins
    - prometheus
  vars:
    app_port: 6060
    service_name: "flask-app"
    #promethus vars:
    alertmanager_host: "localhost"
    alertmanager_port: 9093
    node_exporter_host: "localhost"
    node_exporter_port: 9100
    prometheus_host: "localhost"
    prometheus_port: 9090
    flask_app_host: "localhost"
    flask_app_port: 6060
