---
- name: Deploy Flask Application
  hosts: localhost
  become: yes
  tasks:
    - name: Install system dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-venv
        - git

    - name: Ensure app directory exists
      file:
        path: /opt/flask-app
        state: directory
        owner: jenkins
        group: jenkins

    - name: Copy application files
      copy:
        src: "{{ app_source_dir }}"
        dest: /opt/flask-app
        owner: jenkins
        group: jenkins

    - name: Create virtual environment
      pip:
        virtualenv: /opt/flask-app/venv
        virtualenv_python: python3

    - name: Install Python requirements
      pip:
        virtualenv: /opt/flask-app/venv
        requirements: /opt/flask-app/requirements.txt

    - name: Deploy systemd service
      template:
        src: "{{ ansible_template_dir }}/flask-app.service.j2"
        dest: /etc/systemd/system/{{ service_name }}.service
      vars:
        app_port: "{{ app_port }}"
      notify: Restart Flask Service

  handlers:
    - name: Restart Flask Service
      systemd:
        name: "{{ service_name }}"
        state: restarted
        daemon_reload: yes