---
- name: Deploy Monitoring Stack
  hosts: localhost
  become: yes
  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Configure Prometheus
      template:
        src: "{{ ansible_template_dir }}/prometheus.yml"
        dest: /etc/prometheus/prometheus.yml

    - name: Deploy Prometheus systemd service
      template:
        src: "{{ ansible_template_dir }}/prometheus.service.j2"
        dest: /etc/systemd/system/prometheus.service

    - name: Reload systemd and restart Prometheus
      systemd:
        name: prometheus
        state: restarted
        daemon_reload: yes
        enabled: yes