---
- name: Deploy full infrastructure
  hosts: localhost
  become: yes
  gather_facts: yes
  roles:
    - jenkins
    - prometheus
  vars:
    app_port: 6060
    service_name: "flask-app"
    telegram_bot_token: "dummy"
    telegram_chat_id: "dummy"