---
- name: Create Jenkins data directory
  file:
    path: /var/jenkins_home
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Create initial admin password
  copy:
    content: "{{ jenkins_admin_password }}"
    dest: /var/jenkins_home/secrets/initialAdminPassword
    owner: 1000
    group: 1000
    mode: '0600'

- name: Run Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=true"

- name: Wait for Jenkins initialization
  wait_for:
    port: 8080
    delay: 10
    timeout: 300

- name: Display admin password
  debug:
    msg: "Jenkins admin password: {{ jenkins_admin_password }}"