---
- name: Add Jenkins repository key
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: "jenkins"

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins initialization
  wait_for:
    port: 8080
    delay: 10
    timeout: 120

- name: Install system dependencies
  apt:
    name:
      - python3-pip
      - python3-venv
      - git
    state: present

- name: Create app directory
  file:
    path: /opt/flask-app
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy application files
  copy:
    src: "{{ playbook_dir }}/../app/"
    dest: /opt/flask-app
    owner: root
    group: root
    force: yes

- name: Create virtual environment
  shell: |
    python3 -m venv /opt/flask-app/venv
  args:
    executable: /bin/bash

- name: Install Python requirements
  shell: |
    source /opt/flask-app/venv/bin/activate
    pip install -r /opt/flask-app/requirements.txt
  args:
    executable: /bin/bash

- name: Deploy systemd service
  template:
    src: flask-app.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: root
    group: root
    mode: '0644'

- name: Restart Flask Service
  systemd:
    name: "{{ service_name }}"
    state: restarted
    daemon_reload: yes