version: '3.8'

services:
  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - ci-cd-net

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-cd-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - ci-cd-net

volumes:
  jenkins_data:

networks:
  ci-cd-net: