jenkins:
  systemMessage: "Jenkins Configured as Code"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: "{{ jenkins_admin_password }}"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
  tools:
    git:
      installations:
        - name: git
          home: /usr/bin/git
  jobs:
    - script: >
        pipelineJob('Flask') {
          definition {
            cpsScm {
              scm {
                git {
                  remote {
                    url('https://github.com/nuclear77/theGP.git')
                  }
                  branches('*/main')
                }
              }
              scriptPath('project/jenkins/Jenkinsfile')
            }
          }
        }
unclassified:
  location:
    url: http://{{ ansible_host }}:8080/