- name: Clone app repository
  git:
    repo: "*"
    dest: /opt/app

- name: Install dependencies
  pip:
    requirements: /opt/app/requirements.txt

- name: Start Gunicorn service
  systemd:
    name: gunicorn
    state: started
    enabled: yes