---
- name: Install system dependencies
  apt:
    name:
      - python3-pip
      - python3-venv
      - git
    state: present

- name: Create app directory
  file:
    path: /opt/flask-app
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy application files
  copy:
    src: "{{ playbook_dir }}/../../app/"
    dest: /opt/flask-app
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    force: yes

- name: Create virtual environment
  shell: python3 -m venv /opt/flask-app/venv

- name: Install Python requirements
  shell: |
    . /opt/flask-app/venv/bin/activate
    pip install -r /opt/flask-app/requirements.txt

- name: Deploy systemd service
  template:
    src: flask-app.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: root
    group: root
    mode: '0644'

- name: Start Flask service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes