- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes