---
- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Alertmanager
  systemd:
    name: alertmanager
    state: restarted
    enabled: yes
    daemon_reload: yes